/*
Problem - You are given two strings s and t.
          String t is generated by random shuffling string s and then add one more letter at a random position.
          Return the letter that was added to t.

test case1: Input: s = "abcd", t = "abcde"
            Output: "e"
            Explanation: 'e' is the letter that was added.
            
test case2: Input: s = "", t = "y"
            Output: "y"          
*/

/*
Solution-
 TC = O(t)
 SC = O(1)
*/

class Solution {
    public char findTheDifference(String s, String t) {
        int i=0,result=0;
        for(i = 0 ;i < s.length(); i++){
            result += t.charAt(i);
            result -= s.charAt(i);
        }
        result += t.charAt(i);
        return (char)result;
        /*
        char ch = 0;
        for(char c : s.toCharArray()) ch ^=c;
        for(char c : t.toCharArray()) ch ^=c;
        return ch;
        */
    }
}
